# This is a basic workflow to help you get started with Actions

name: CI CD Deploy
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - feature/*
      - chore/*
      - hotfix/*
      - release/*
  workflow_dispatch:
    inputs:
      job:
        description: 'Deploy to prod manually'
        required: true
        default: 'deploy-prod'

jobs:
  init:
    name: ğŸº Init app on github actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']

    steps:
      - name: â˜•ï¸ Copy repository
        uses: actions/checkout@v2

      - name: ğŸ¦š Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‰ Init with node
        run: echo "Hello init project here"

  test:
    name: ğŸº Testing app on github actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    needs: init

    steps:
      - name: â˜•ï¸ Copy repository
        uses: actions/checkout@v2

      - name: ğŸ¦š Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‰ Test with node
        run: echo "Hello Test Code"

  deploy-sit:
    name: ğŸº Deploy app SIT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    needs: [init, test]

    steps:
      - name: â˜•ï¸ Copy repository
        uses: actions/checkout@v2

      - name: ğŸ¦š Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‰ Echo with node on sit
        run: echo "Hello Sit"

  deploy-staging:
    name: ğŸº Deploy app Staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    needs: [init, test]

    steps:
      - name: â˜•ï¸ Copy repository
        uses: actions/checkout@v2

      - name: ğŸ¦š Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‰ Echo with node on sit
        run: echo "Hello staging"

  deploy-prod:
    name: ğŸº Deploy app Prod
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-prod'}}
    strategy:
      matrix:
        node-version: ['14', '16']
    needs: [init, test]

    steps:
      - name: â˜•ï¸ Copy repository
        uses: actions/checkout@v2

      - name: ğŸ¦š Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‰ Echo with node on sit
        run: echo "Hello Sit"